# Generated by Django 6.0.5 on 2026-05-24 11:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestedRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP ERP Fuel & Procurement'), ('UTILITY', 'Utility Electricity Bill'), ('TRAVEL', 'Corporate Travel API')], max_length=50)),
                ('raw_data', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved & Locked'), ('FAILED', 'Ingestion Failed'), ('SUSPICIOUS', 'Suspicious / Flagged')], default='PENDING', max_length=50)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('uploaded_by', models.CharField(default='System / API', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('api_key', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1 (Direct)'), ('SCOPE_2', 'Scope 2 (Indirect)'), ('SCOPE_3', 'Scope 3 (Other Indirect)')], max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('activity_date', models.DateField()),
                ('raw_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('raw_unit', models.CharField(max_length=50)),
                ('normalized_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('normalized_unit', models.CharField(max_length=50)),
                ('co2e_kg', models.DecimalField(decimal_places=4, max_digits=18)),
                ('source_identifier', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source_row', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_record', to='api.ingestedrow')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_data', to='api.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='ingestedrow',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingested_rows', to='api.tenant'),
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='System', max_length=255)),
                ('action', models.CharField(max_length=100)),
                ('previous_status', models.CharField(blank=True, max_length=50, null=True)),
                ('new_status', models.CharField(max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_records', to='api.ingestedrow')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trails', to='api.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PlantLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('grid_emission_factor', models.DecimalField(decimal_places=4, default=0.35, max_digits=8)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='api.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'plant_code')},
            },
        ),
        migrations.CreateModel(
            name='FacilityLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=100)),
                ('meter_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('grid_emission_factor', models.DecimalField(decimal_places=4, default=0.25, max_digits=8)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='api.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'account_number', 'meter_number')},
            },
        ),
    ]
